name: Publish Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2.0.2

      - name: Set up JDK 17
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Stage Local
        run: ./gradlew -V publish

      - name: Publish package
        run: ./gradlew -V --no-parallel uploadDocs jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JOINFACES_SIGNING_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JOINFACES_SIGNING_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JOINFACES_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_joinfacesDocsUser: ${{ secrets.JOINFACES_DOCS_USER }}
          ORG_GRADLE_PROJECT_joinfacesDocsPass: ${{ secrets.JOINFACES_DOCS_PASS }}
